/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.OyenteMenu;

/**
 *
 * @author Manuel Angel Muñoz S
 */
public class VentanaDiagramas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDiagramas
     */
    public VentanaDiagramas(String nombre){
        super(nombre);
        initComponents();
    }
    public VentanaDiagramas() {
        initComponents();
    }
    public void addEventos(OyenteMenu o){
        salir.addActionListener(o);
        
        inicio.addActionListener(o);
        codigo.addActionListener(o);
        lectura.addActionListener(o);
        si.addActionListener(o);
        fin.addActionListener(o);
        hacermientras.addActionListener(o);
        mientras.addActionListener(o);
        ciclo.addActionListener(o);
        //editar
        reacomoda.addActionListener(o);
        seleccionaTodos.addActionListener(o);
        compilar.addActionListener(o);
        imprimir.addActionListener(o);
        abrir.addActionListener(o);
        guardar.addActionListener(o);
        guardarComo.addActionListener(o);
        codigo1.addActionListener(o);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        insertar = new javax.swing.JMenu();
        inicio = new javax.swing.JMenuItem();
        codigo = new javax.swing.JMenuItem();
        lectura = new javax.swing.JMenuItem();
        si = new javax.swing.JMenuItem();
        imprimir = new javax.swing.JMenuItem();
        hacermientras = new javax.swing.JMenuItem();
        mientras = new javax.swing.JMenuItem();
        ciclo = new javax.swing.JMenuItem();
        fin = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        reacomoda = new javax.swing.JMenuItem();
        seleccionaTodos = new javax.swing.JMenuItem();
        run = new javax.swing.JMenu();
        compilar = new javax.swing.JMenuItem();
        codigo1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jLabel1.setText("jLabel1");

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenu12.setText("File");
        jMenuBar5.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar5.add(jMenu13);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("CANMASA");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_END);

        archivo.setText("Archivo");

        abrir.setText("Abrir");
        archivo.add(abrir);

        guardar.setText("Guardar");
        archivo.add(guardar);

        guardarComo.setText("Guardar como");
        guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComoActionPerformed(evt);
            }
        });
        archivo.add(guardarComo);

        salir.setText("Salir");
        archivo.add(salir);

        jMenuBar1.add(archivo);

        insertar.setText("Insertar");

        inicio.setText("Inicio");
        insertar.add(inicio);

        codigo.setText("Codigo");
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        insertar.add(codigo);

        lectura.setText("Lectura");
        insertar.add(lectura);

        si.setText("Si");
        insertar.add(si);

        imprimir.setText("Imprimir");
        insertar.add(imprimir);

        hacermientras.setText("Hacermientras");
        insertar.add(hacermientras);

        mientras.setText("Mientras");
        insertar.add(mientras);

        ciclo.setText("Ciclo");
        insertar.add(ciclo);

        fin.setText("Fin");
        insertar.add(fin);

        jMenuBar1.add(insertar);

        editar.setText("Editar");

        reacomoda.setText("Reacomoda");
        editar.add(reacomoda);

        seleccionaTodos.setText("Selecciona todos");
        editar.add(seleccionaTodos);

        jMenuBar1.add(editar);

        run.setText("Run");

        compilar.setText("Compilar");
        run.add(compilar);

        codigo1.setText("Convertidor");
        codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo1ActionPerformed(evt);
            }
        });
        run.add(codigo1);

        jMenuBar1.add(run);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo1ActionPerformed
        // TODO add your handling code here:
          new Muestracodigo().setVisible(true); 
        
        
    }//GEN-LAST:event_codigo1ActionPerformed

    private void guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarComoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDiagramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDiagramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDiagramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDiagramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDiagramas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenuItem ciclo;
    private javax.swing.JMenuItem codigo;
    private javax.swing.JMenuItem codigo1;
    private javax.swing.JMenuItem compilar;
    private javax.swing.JMenu editar;
    private javax.swing.JMenuItem fin;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JMenuItem hacermientras;
    private javax.swing.JMenuItem imprimir;
    private javax.swing.JMenuItem inicio;
    private javax.swing.JMenu insertar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem lectura;
    private javax.swing.JMenuItem mientras;
    private javax.swing.JMenuItem reacomoda;
    private javax.swing.JMenu run;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem seleccionaTodos;
    private javax.swing.JMenuItem si;
    // End of variables declaration//GEN-END:variables
}
