/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package modelos.compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int entero = 5;
  /** RegularExpression Id. */
  int flotante = 6;
  /** RegularExpression Id. */
  int doble = 7;
  /** RegularExpression Id. */
  int caracter = 8;
  /** RegularExpression Id. */
  int largo = 9;
  /** RegularExpression Id. */
  int OP_SUMA = 10;
  /** RegularExpression Id. */
  int OP_RESTA = 11;
  /** RegularExpression Id. */
  int NUMERO = 12;
  /** RegularExpression Id. */
  int NUM_DEC = 13;
  /** RegularExpression Id. */
  int MODULO = 14;
  /** RegularExpression Id. */
  int IGUAL = 15;
  /** RegularExpression Id. */
  int POR = 16;
  /** RegularExpression Id. */
  int ENTRE = 17;
  /** RegularExpression Id. */
  int FIN = 18;
  /** RegularExpression Id. */
  int MENOR = 19;
  /** RegularExpression Id. */
  int MAYOR = 20;
  /** RegularExpression Id. */
  int ABRE = 21;
  /** RegularExpression Id. */
  int CIERRA = 22;
  /** RegularExpression Id. */
  int COMA = 23;
  /** RegularExpression Id. */
  int COMILLA = 24;
  /** RegularExpression Id. */
  int CORCH_ABRE = 25;
  /** RegularExpression Id. */
  int CORCH_CIER = 26;
  /** RegularExpression Id. */
  int LETRA = 27;
  /** RegularExpression Id. */
  int CARACTER_LITERAL = 28;
  /** RegularExpression Id. */
  int VARIABLE = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"entero\"",
    "\"flotante\"",
    "\"doble\"",
    "\"caracter\"",
    "\"largo\"",
    "\"+\"",
    "\"-\"",
    "<NUMERO>",
    "<NUM_DEC>",
    "\"%\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "<LETRA>",
    "<CARACTER_LITERAL>",
    "<VARIABLE>",
  };

}
