/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package modelos.compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int entero = 1;
  /** RegularExpression Id. */
  int flotante = 2;
  /** RegularExpression Id. */
  int doble = 3;
  /** RegularExpression Id. */
  int caracter = 4;
  /** RegularExpression Id. */
  int largo = 5;
  /** RegularExpression Id. */
  int OP_SUMA = 6;
  /** RegularExpression Id. */
  int OP_RESTA = 7;
  /** RegularExpression Id. */
  int NUMERO = 8;
  /** RegularExpression Id. */
  int NUM_DEC = 9;
  /** RegularExpression Id. */
  int MODULO = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int POR = 12;
  /** RegularExpression Id. */
  int ENTRE = 13;
  /** RegularExpression Id. */
  int FIN = 14;
  /** RegularExpression Id. */
  int MENOR = 15;
  /** RegularExpression Id. */
  int MAYOR = 16;
  /** RegularExpression Id. */
  int ABRE = 17;
  /** RegularExpression Id. */
  int CIERRA = 18;
  /** RegularExpression Id. */
  int COMA = 19;
  /** RegularExpression Id. */
  int COMILLA = 20;
  /** RegularExpression Id. */
  int CORCH_ABRE = 21;
  /** RegularExpression Id. */
  int CORCH_CIER = 22;
  /** RegularExpression Id. */
  int LETRA = 23;
  /** RegularExpression Id. */
  int CARAC_ESP = 24;
  /** RegularExpression Id. */
  int VARIABLE = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"entero\"",
    "\"flotante\"",
    "\"doble\"",
    "\"caracter\"",
    "\"largo\"",
    "\"+\"",
    "\"-\"",
    "<NUMERO>",
    "<NUM_DEC>",
    "\"%\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "<LETRA>",
    "<CARAC_ESP>",
    "<VARIABLE>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
